name: TCR-env
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - numpy=1.24.4
  - numba=0.57.1
  - pandas=2.1.0
  - tqdm=4.66.1
  - transformers=4.32.1  
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - scipy=1.11.2
  - torchvision=0.15.2
  - torchaudio=2.0.2

